# Name of the speller package in various languages.
# The default is English + autonym:
[speller.name]
en = "Viena Karelian spellchecker"
krl = "Autonym spellchecker"

# Description of the speller package in various languages.
# The default is English + autonym:
[speller.description]
en = "A spellchecker for Viena Karelian, made by members of the language community, and by the Divvun and Giellatekno groups at UiT The Arctic University of Norway"
krl = "TRANSLATE: A spellchecker for Viena Karelian, made by members of the language community, and by the Divvun and Giellatekno groups at UiT The Arctic University of Norway"

[macos]
system_pkg_id = "no.divvun.MacDivvun.krl"

[windows]
system_product_code = "{5BAF43DB-E2A1-455C-BBF7-7CF35273765A}_is1"
legacy_product_codes = [
    { value = "C3E512A3-842A-4B99-9F4F-BB7157883815", kind = "nsis" },
    { value = "169B9D33-75C1-4976-9DC2-CED13D7B9803", kind = "nsis" }
]
extra_locales = { krl-FI = "krl" }

[package.speller]
name = "Viena Karelian"
version = "0.1.1"

[package.grammar]
name = "Viena Karelian"
version = "0.1.0"

[package.tts-text-proc]
name = "Viena Karelian"
version = "0.1.0"
