template = "https://github.com/giellalt/template-lang-und"
rev_id = 277
template_sha = "c0f383639e245d1daebce6e2006904e442eef1fd"

[replacements]
__GLOTTOLOG_ID__ = "kare1335"
__REPO__ = "lang-krl"
__UND2C__ = "krl"
__UNDEFINED__ = "Viena Karelian"
__UND__ = "krl"
