template = "https://github.com/giellalt/template-lang-und"
rev_id = 256
template_sha = "4e2ddf168a2aaf68d2c29db9e79e44e1dc4c2b76"

[replacements]
__GLOTTOLOG_ID__ = "kare1335"
__REPO__ = "lang-krl"
__UND2C__ = "krl"
__UNDEFINED__ = "Viena Karelian"
__UND__ = "krl"
