template = "https://github.com/giellalt/template-lang-und"
rev_id = 261
template_sha = "eaa0621ef7403d653282fabf176060ed3c95ebf4"

[replacements]
__GLOTTOLOG_ID__ = "kare1335"
__REPO__ = "lang-krl"
__UND2C__ = "krl"
__UNDEFINED__ = "Viena Karelian"
__UND__ = "krl"
